### PR TITLE
Temporarily mark CoreML export test as xfail

### PR DESCRIPTION
**Pull request by znation**
This will suppress the failure in #1332. When that issue is fixed, we
should remove the xfail.

### CODE REVIEW

**Comment by hoytak** [comment]
Thanks,@znation!  Appreciate you covering for me here.

**Comment by TobyRoseman** [comment]
@hoytak - do additional tests need to be marked as `xfail` I just got another failure from the same file:

```
self = <turicreate.test.test_coreml_export.CoreMLExportTest testMethod=test_svm_classifier>

    def test_svm_classifier(self):
        for code_string in ["b"*40, "nnnn", "v", "d", "A", "bnsCvAd"]:
            train, test = self.generate_data("classification", 100, code_string)
            model = tc.svm_classifier.create(train, "target", validation_set = None)
            model.evaluate(test)  # Previous regression -- this caused errors.
>           self._test_coreml_export(model, test, False, has_probability = False)

test_coreml_export.py:190: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_coreml_export.py:103: in _test_coreml_export
    self.assertAlmostEqual(coreml_prediction["target"], tc_prediction, delta = 1e-5)
E   AssertionError: 1L != 0 within 1e-05 delta
```

**Comment by nickjong** [comment]
Yes, I’ve seen this on linear regression, SVM, and the three logistic classifier variants

**Comment by znation** [comment]
Thanks @TobyRoseman and @nickjong. I'll xfail those as well on 10.13.

**Pull request merged**
