### PR TITLE
upgrade AWS s3 sdk

### PR DESCRIPTION
**Pull request by guihao-liang**

### CODE REVIEW

**Comment by TobyRoseman** [comment]
Related #3025

@guihao-liang - it would be helpful if you could include here what version of the SDK this pull request syncs.

**Comment by guihao-liang** [comment]
> Related #3025
> 
> @guihao-liang - it would be helpful if you could include here what version of the SDK this pull request syncs.

I have a README that describes the versioning in detail. Currently, the build is still broken, I'm working with @hoytak on debugging it.

**Comment by TobyRoseman** [comment]
> > Related #3025
> > @guihao-liang - it would be helpful if you could include here what version of the SDK this pull request syncs.
> 
> I have a README that describes the versioning in detail. Currently, the build is still broken, I'm working with @hoytak on debugging it.

I assume you mean `src/external/aws-sdk-cpp/README.md`. I looked at that file before my first comment. It wasn't clear to me that was something you added. Perhaps it would be better to add a `aws-sdk-cpp` section to the `src/external/README.md`, and add that information there.

**Comment by guihao-liang** [comment]
> > > Related #3025
> > > @guihao-liang - it would be helpful if you could include here what version of the SDK this pull request syncs.
> > 
> > 
> > I have a README that describes the versioning in detail. Currently, the build is still broken, I'm working with @hoytak on debugging it.
> 
> I assume you mean `src/external/aws-sdk-cpp/README.md`. I looked at that file before my first comment. It wasn't clear to me that was something you added. Perhaps it would be better to add a `aws-sdk-cpp` section to the `src/external/README.md`, and add that information there.

will do after the linux build passes.

**Comment by guihao-liang** [comment]
@TobyRoseman added the version info.

**Comment by TobyRoseman** [comment]
> @TobyRoseman added the version info.

Great, thanks. However it looks like that info is still under `ssrc/external/aws-sdk-cpp/README.md` rather than included in `src/external/README.md`.

**Comment by guihao-liang** [comment]
> > @TobyRoseman added the version info.
> 
> Great, thanks. However it looks like that info is still under `ssrc/external/aws-sdk-cpp/README.md` rather than included in `src/external/README.md`.

I see. Sorry I didn't read it carefully. Add a hyperlink inside of src/external/README.md.

**Pull request merged**
