### PR TITLE
Changed test to be far less intensive.

### PR DESCRIPTION
**Pull request by hoytak**
Still tests the functionality, but uses a much smaller dataset.

### CODE REVIEW

**Comment by TobyRoseman** [comment]
@hoytak - looks like most of the changes here are stylistic. Are these done by [black](https://github.com/psf/black), our new code formatter?

**Comment by hoytak** [comment]
PR updated.

**Comment by nickjong** [comment]
Do we still want/need this PR?

**Comment by hoytak** [comment]
I assume we do -- it's just making the test more of a unit test.  I wasn't following this work to be honest, though.

**Comment by TobyRoseman** [comment]
I agree, we should still merge this change. It should make running our unit tests a few minutes quicker.

**Pull request merged**
