### PR TITLE
Delete unused C++ code

### PR DESCRIPTION
**Pull request by TobyRoseman**

### CODE REVIEW

**Comment by guihao-liang** [comment]
It might be fine to leave these header-only utils there in case of future usage.

**Comment by TobyRoseman** [comment]
> It might be fine to leave these header-only utils there in case of future usage.

What would the benefit of that be? These files are under source control, so we can recover them whenever we what. Right now having them around is just extra code to worry about and it's confusing.

**Comment by guihao-liang** [comment]
> > It might be fine to leave these header-only utils there in case of future usage.
> 
> What would the benefit of that be? These files are under source control, so we can recover them whenever we what. Right now having them around is just extra code to worry about and it's confusing.

those headers are not even compiled. Besides that, since those files are rarely modified, the git blob store should be very efficient to track it and store it.

**Comment by nickjong** [comment]
Unless we think we are likely to use this stuff, let’s not keep it around just because git is efficient at keeping it. The cost is more conceptual complexity and clarity, not build performance

**Pull request merged**
