### PR TITLE
Fix for bit mask to make corner case more portable.

### PR DESCRIPTION
**Pull request by hoytak**
Turns out uint64_t(1) << 64 isn't actually well defined.

### CODE REVIEW

**Comment by ylow** [comment]
There is possibly a branch free version
```
return (T(1) << n_bits) - 1 - (n_bits == bitsizeof(T));
```

**Comment by hoytak** [comment]
> There is possibly a branch free version
> 
> ```
> return (T(1) << n_bits) - 1 - T(n_bits == bitsizeof(T));
> ```

But the first expression sometimes is zero and sometimes a no-op, so this wouldn't work either. 

We could use the branch free version in https://stackoverflow.com/questions/1392059/algorithm-to-generate-bit-mask, though.

**Comment by ylow** [comment]
What do you mean by no-op? 
This seems to work fine.

```
#include <cstdint>
#include <iostream>
#include <ios>

template <typename T>
T bitmask(int n_bits) {
  return (T(1) << n_bits) - 1 - T(n_bits == 8 * sizeof(T));
}
int main() {
  std::cout << std::hex << bitmask<int64_t>(0) << "\n"
                        << bitmask<int64_t>(1) << "\n"
                        << bitmask<int64_t>(63) << "\n"
                        << bitmask<int64_t>(64) << "\n"
                        << bitmask<uint64_t>(0) << "\n"
                        << bitmask<uint64_t>(1) << "\n"
                        << bitmask<uint64_t>(63) << "\n"
                        << bitmask<uint64_t>(64) << "\n"
                        << bitmask<int32_t>(0) << "\n"
                        << bitmask<int32_t>(1) << "\n"
                        << bitmask<int32_t>(31) << "\n"
                        << bitmask<int32_t>(32) << "\n"
                        << bitmask<uint32_t>(0) << "\n"
                        << bitmask<uint32_t>(1) << "\n"
                        << bitmask<uint32_t>(31) << "\n"
                        << bitmask<uint32_t>(32) << "\n";
}
```

Essentially, if n_bits == bitsizeof(T), (T(1) << n_bits) - 1 == 0, so we minus 1 again to get -1.

Though technically this does depend on undefined behavior. Compiling with -fsanitize=undefined does give errors like
```
runtime error: shift exponent 64 is too large for 64-bit type 'long long'
```

Your branching version is fine. Will be great to have some tests for this.

**Comment by hoytak** [comment]
On my machine, lldb says your expression yields the equivalent of -2.

Better version, branch free, no undefined behavior.  This one I'm proud of. 

```
template <typename T>
static inline T bit_mask(uint64_t n_bits, _ENABLE_IF_UINT(T)) {
  return (~T(0)) >> ((-n_bits) & (bitsizeof(T) - 1) );
}
```

**Pull request merged**
