### PR TITLE
Updated syntax for Python 2.7 and 3.6 Build Breaks

### PR DESCRIPTION
**Pull request by abhishekpratapa**
- Updated the testing syntax for Python 2.7 and 3.6 Build Breaks in master.

### CODE REVIEW

**Comment by abhishekpratapa** [comment]
Fixes #2109

**Comment by Jarvi-Izana** [comment]
Thanks for the catch! That's weird because I ran the local test with 3.6 successfully.

**Comment by abhishekpratapa** [comment]
> Thanks for the catch! That's weird because I ran the local test with 3.6 successfully.

Normally this wouldn't happen, we have something inconsistent in our Travis Builds right now. We test the wheel that we've built with Python 3.6 on a Python 2.7 machine.

That's the reason for the build breaks on both Python 2.7 and Python 3.6 in travis. The tests are running in 2.7.

**Comment by Jarvi-Izana** [comment]
glad to know the context! That's super helpful!

**Pull request merged**
