### PR TITLE
enforce python style check

### PR DESCRIPTION
**Pull request by guihao-liang**
Let's enforce the python style check before the build. People like freestyle even though I provide hooks for them to use. I'd better provide a defensive way to remind people using black style.

### CODE REVIEW

**Comment by guihao-liang** [comment]
only enforce on python3.7 since Travis uses 3.7. 

No need to rigidly enforce style check on all python versions since build can continue to run and people can get useful build information even though the style check fails. In this way, the number of push commits will be reduced by half, on average.

**Comment by TobyRoseman** [comment]
The code formatting changes all look good.

I'm not sure integrating `black` with `make_wheel.sh` is the best route. It would be better to let developers know about the formatting changes sooner. Is there a way to integrate `black` with `make`?

**Comment by guihao-liang** [comment]
> The code formatting changes all look good.
> 
> I'm not sure integrating `black` with `make_wheel.sh` is the best route. It would be better to let developers know about the formatting changes sooner. Is there a way to integrate `black` with `make`?

right, that's an option. or just use black command.

**Comment by guihao-liang** [comment]
@TobyRoseman black only supports python3.6+, I don't this a make target is appropriate to do this, and I just tried. How about documenting it somewhere?

**Comment by guihao-liang** [comment]
```
pycodestyle data_structures --max-line-length=90 --max-doc-length=120 --ignore=E501,W503,E722,E266,E203,W505
data_structures/sarray.py:3268:21: E712 comparison to True should be 'if cond is True:' or 'if cond:'
data_structures/sarray.py:4584:43: E711 comparison to None should be 'if cond is None:'
data_structures/sframe.py:880:34: E721 do not compare types, use 'isinstance()'
data_structures/sframe.py:886:37: E721 do not compare types, use 'isinstance()'
data_structures/sframe.py:1908:61: E721 do not compare types, use 'isinstance()'
data_structures/sframe.py:1990:13: E731 do not assign a lambda expression, use a def
data_structures/sframe.py:2028:13: E731 do not assign a lambda expression, use a def
data_structures/sframe.py:2031:13: E731 do not assign a lambda expression, use a def
data_structures/sframe.py:2331:1: E101 indentation contains mixed spaces and tabs
data_structures/sframe.py:2331:1: W191 indentation contains tabs
data_structures/sframe.py:2332:1: W191 indentation contains tabs
data_structures/sframe.py:2332:2: E101 indentation contains mixed spaces and tabs
data_structures/sframe.py:2333:1: W191 indentation contains tabs
data_structures/sframe.py:2333:2: E101 indentation contains mixed spaces and tabs
data_structures/sframe.py:2334:1: E101 indentation contains mixed spaces and tabs
data_structures/sframe.py:3757:16: E713 test for membership should be 'not in'
data_structures/sframe.py:3825:16: E713 test for membership should be 'not in'
data_structures/sframe.py:3883:16: E713 test for membership should be 'not in'
data_structures/sframe.py:4360:32: E713 test for membership should be 'not in'
data_structures/sframe.py:4408:32: E713 test for membership should be 'not in'
data_structures/sframe.py:4752:43: E711 comparison to None should be 'if cond is None:'
data_structures/sframe.py:5123:32: E712 comparison to True should be 'if cond is True:' or 'if cond:'
data_structures/sgraph.py:84:12: E714 test for object identity should be 'is not'
data_structures/sgraph.py:139:12: E714 test for object identity should be 'is not'
data_structures/sgraph.py:1245:8: E713 test for membership should be 'not in'
data_structures/sketch.py:186:54: E231 missing whitespace after ','
```

I just use another tool to check our codebase. Well, there are too many problems and I don't have time for fixing them at one time. There's a long way to apply `PEP8` to our codebase. Really embrace our codebase with pre-commit hooks.

Anyway, let's just merge the python code without adding checks.

**Comment by TobyRoseman** [comment]
> @TobyRoseman black only supports python3.6+, I don't this a make target is appropriate to do this, and I just tried. How about documenting it somewhere?

It looks like black also support Python 2.7 and 3.5. See the [`--target-version` option](https://github.com/psf/black#command-line-options).

**Comment by guihao-liang** [comment]
> > @TobyRoseman black only supports python3.6+, I don't this a make target is appropriate to do this, and I just tried. How about documenting it somewhere?
> 
> It looks like black also support Python 2.7 and 3.5. See the [`--target-version` option](https://github.com/psf/black#command-line-options).

> Black can be installed by running pip install black. **It requires Python 3.6.0+ to run** but you can reformat Python 2 code with it, too.

**Pull request merged**
