### PR TITLE
Docs: add notes on conda install, fix whitespace

### PR DESCRIPTION
**Pull request by pavopax**
I have conda installed, which created some issues when trying to install turi using system pip, as recommended.

I provide some notes for conda users which may be helpful.

(I think this assumes I installed system pip in the past. Let's discuss more?)

### CODE REVIEW

**Comment by srikris** [comment]
I'm surprised that you ran into issues with conda. Could you elaborate more?

**Comment by igiloh** [comment]
Hi @pavopax, thank you for pointing this out,
Have you tried using conda's built-in virtualenv, using `conda create`?

I've just tried these steps, and they seem to work on my system:
```
conda create -n venv python=2.7 anaconda
source activate venv
pip install --upgrade pip
pip install turicreate
python -c "import turicreate as tc ; print tc.__version__"
```

**Comment by igiloh** [comment]
Thanks for the input @pavopax !
I wonder whether we should add a conda option for the main README.md. My only concern is that extending the readme with too many options might make it more confusing.

**Comment by pavopax** [comment]
personally, I was confused by "system pip" which to me basically meant "don't use Conda"

but that may be just me

in terms of what to recommend, I am no expert and you/the team would know better, so I have no further recommendations! thanks for the follow-ups!

**Comment by igiloh** [comment]
Thank you for all of your inputs @pavopax.
I'll close this PR now and start a new one with the relevant documentation updates.

**Pull request closed without merging**
