### PR TITLE
Allowed CMAKE_OSX_DEPLOYMENT_TARGET to be set externally.

### PR DESCRIPTION
**Pull request by hoytak**

### CODE REVIEW

**Comment by nickjong** [comment]
Thinking about this some more, I'm not sure why we need this. The deployment target for our Objective-C libraries should not need to vary any more than the deployment target of the frameworks that we depend on, right? For example, CoreML presumably has a deployment target of 10.13, but binaries with any deployment target can link against it. (As long as they use runtime checks to avoid using it on pre-10.13 systems.)

**Comment by znation** [comment]
@hoytak Can you address @nickjong's comment? This change looks fine to me, but it sounds like it may not be necessary.

**Comment by srikris** [comment]
@hoytak @nickjong Can we close on this. Are we taking this change or not?

**Comment by hoytak** [comment]
Let me investigate more on this -- I believe we can drop it.

**Pull request closed without merging**
