### PR TITLE
Removes deprecated warning on import turicreate

### PR DESCRIPTION
**Pull request by shreyajain17**
Python 2.7.16

### CODE REVIEW

**Comment by TobyRoseman** [comment]
Was this not part of the 5.8 release?

**Comment by shreyajain17** [comment]
It was in the 5.8 branch but not in master. So I just added it.

**Comment by TobyRoseman** [comment]
@shreyajain17 - Great! Thanks for letting me know, and thanks for find and fixing this in the first place.

Perhaps in the in the future, it would be better to review and merge it into master. Then cherry-pick it into the release branch.

**Comment by shreyajain17** [comment]
Yeah I agree.

**Pull request merged**
