### PR TITLE
Added option in configure script to specify python executable.

### PR DESCRIPTION
**Pull request by hoytak**
Now, to set up everything with, e.g. python3.7, you can just use:

```
./configure --python=`which python3.7` 
```

This allows one to easily compile for certain python versions.

### CODE REVIEW

**Comment by nickjong** [comment]
In https://github.com/apple/turicreate/pull/783 we explicitly removed the command line option to specify Python version, replacing it with `--virtualenv`. Does that not satisfy your use case?

**Comment by TobyRoseman** [comment]
@hoytak - take a look at #2079 I believe this is the correct way to add python 3.7 support

**Comment by hoytak** [comment]
> @hoytak - take a look at #2079 I believe this is the correct way to add python 3.7 support

@TobyRoseman -- How does that add support for using a system python 3.7?  

Here's my use case.  On linux, with no docker.  The python 3.7 executable is available only with python3.7 explicitly.  virtualenv is installed through python 2.7, with no virtualenv that explicitly defaults to the python I want.  

With this change, it just pushes the python version support to the virtualenv executable, which works across python arguments.  In addition, it mimics the command line option for virtualenv.

**Comment by hoytak** [comment]
> In #783 we explicitly removed the command line option to specify Python version, replacing it with `--virtualenv`. Does that not satisfy your use case?

Hey @nickjong, this way does not work if there is no virtualenv executable installed that defaults to the correct python environment.  Virtualenv is designed to work independent of it's base python version through use of the --python argument, so there isn't really a need to have multiple virtualenv versions installed.  I could use the existing command through setting `./configure --virtualenv "virtualenv --python=python3.7"`, but I don't think that's very intuitive (or should be documented). 

(Also, I like this way as it mimics how virtualenv handles it as well.)

**Comment by TobyRoseman** [comment]
@hoytak - To get python 3.7 working on Linux without docker just makes sure that the virtualenv in your path is for python 3.7. Or pass in that virtual environment using the `--virtualenv` parameter.

**Comment by hoytak** [comment]
> @hoytak - To get python 3.7 working on Linux without docker just makes sure that the virtualenv in your path is for python 3.7. Or pass in that virtual environment using the `--virtualenv` parameter.

virtualenv is python version independent, so there isn't a virtualenv for a particular python version.  Yes, it defaults to the one it was installed with, but it works with any version.  See my comments above.

**Comment by znation** [comment]
> > @hoytak - To get python 3.7 working on Linux without docker just makes sure that the virtualenv in your path is for python 3.7. Or pass in that virtual environment using the `--virtualenv` parameter.
> 
> virtualenv is python version independent, so there isn't a virtualenv for a particular python version. Yes, it defaults to the one it was installed with, but it works with any version. See my comments above.

And that's exactly why we don't need a code change to specify a Python version.

`./configure --virtualenv="virtualenv --python=\`which python3.7\`` should work in current master.

**Comment by znation** [comment]
Or

```
export VIRTUALENV="virtualenv --python=`which python3.7`"
./configure
```

See https://github.com/apple/turicreate/blob/master/BUILD.md#compiling for other variations. We can list these variations there if it helps.

**Comment by hoytak** [comment]
Yes, we can do that; it would probably be good to document it at least.  I just thought this would make the flow much easier and more intuitive; I don't have to read the docs or understand more advanced details of virtualenv to select the python version I want to work with.  As it is, I don't think it's intuitive or obvious how to do it (which I like).

**Comment by znation** [comment]
> Yes, we can do that; it would probably be good to document it at least. I just thought this would make the flow much easier and more intuitive; I don't have to read the docs or understand more advanced details of virtualenv to select the python version I want to work with. As it is, I don't think it's intuitive or obvious how to do it (which I like).

I was going more for robust and consistent than intuitive or obvious. For instance, what happens if you specify:

```
./configure --virtualenv="virtualenv --python=python2" --python=python3.6
```

The reason I omitted `--python` in #783 was so that there would be exactly one way to specify Python version (through virtualenv command), and no ambiguity about the behavior. For most users, most of the time, the default `virtualenv` creates a Python environment in the desired Python version, and in my experience, when users want to override that, they usually expect to specify a different virtualenv vs. using their existing virtualenv (installed in the site-packages of a particular Python version) with a different Python version.

**Comment by hoytak** [comment]
With discussion, it seems we can just do ./configure --virtualenv="virtualenv --python=python3.7"` to do this, so not doing this enhancement.

**Pull request closed without merging**
