### PR TITLE
Remove unnecessary trailing semicolons

### PR DESCRIPTION
**Pull request by delirious-lettuce**

### CODE REVIEW

**Comment by TobyRoseman** [comment]
@delirious-lettuce - thanks for another great pull request. The changes look good and the unit tests pass. However you've edited three external source files. Editing these files will make it difficult when we want to update to a newer version of these projects.

Please revert the two files you've changed under `src/nnvm` and the one file under `src/xgboost`.

Currently, it's confusing what is and is not external. We've just created #87 to track that issue.

**Comment by delirious-lettuce** [comment]
@TobyRoseman ,

My mistake! I was avoiding everything under `deps` but I see what you are saying. I will revert the changes made in those files you mentioned ASAP.

**Comment by TobyRoseman** [comment]
Thanks @delirious-lettuce

**Comment by delirious-lettuce** [comment]
@TobyRoseman ,

No problem, thanks for your time!

**Pull request merged**
