### PR TITLE
Added missing __bridge symbol.

### PR DESCRIPTION
**Pull request by hoytak**

### CODE REVIEW

**Comment by nickjong** [comment]
Why is this needed?

If it's not needed for 5.3, can we hold off until we finish releasing?

**Comment by znation** [comment]
It seems to be needed on newest (edge) clang, but I'm actually confused why existing clang builds didn't warn us about this. The build passes without this fix on both my machine and our builds, so I think let's take this fix after we release 5.3.

**Comment by hoytak** [comment]
@znation -- can you approve this?

**Comment by znation** [comment]
@hoytak Approved!

**Pull request merged**
