### PR TITLE
reduce duplicated code

### PR DESCRIPTION
**Pull request by guihao-liang**

### CODE REVIEW

**Comment by TobyRoseman** [comment]
It looks like commits from some of your other PRs are included in this PR.

I think removing duplicated code is great, but let's not worry about merging this pull request until after 6.2.

**Comment by guihao-liang** [comment]
I think it's the right time to merge my second last S3 PR. @TobyRoseman

**Comment by TobyRoseman** [comment]
> I think it's the right time to merge my second last S3 PR. @TobyRoseman

@guihao-liang - is this your second to last S3 PR? Or are you referring to something else?

**Comment by guihao-liang** [comment]
> > I think it's the right time to merge my second last S3 PR. @TobyRoseman
> 
> @guihao-liang - is this your second to last S3 PR? Or are you referring to something else?

nope, I need to move on to other projects in 6.3. I need to refresh my brain and clean all S3 stuff.

**Pull request merged**
