### PR TITLE
Userguide rec improved

### PR DESCRIPTION
**Pull request by shantanuchhabra**
Added a screenshot for dragging and dropping libRecommender.dylib

### CODE REVIEW

**Comment by znation** [comment]
@shantanuchhabra What is going on with your commit history? 😄 Your PRs always have like 30 commits in them. Please make sure you're branching off of latest public master, when you are getting ready to put up a PR.

**Comment by shantanuchhabra** [comment]
I'm looking into that, I thought I was branching off of latest master..

**Comment by znation** [comment]
P.S. For screenshots, please follow the instructions [here](https://support.apple.com/en-us/ht201361) for a screenshot of a single window. It'll get a nice drop shadow effect automatically (which looks better than a cropped screenshot).

**Comment by shantanuchhabra** [comment]
Please see #712

**Pull request closed without merging**
