### PR TITLE
Fixed coremltools to non-beta 3.0

### PR DESCRIPTION
**Pull request by hoytak**
Fixes our coremltools dependencies to the non-beta version of 3.0 to minimize risk in releasing 6.0.

### CODE REVIEW

**Comment by hoytak** [comment]
This one is the low-risk change for 6.0, the other PR can go in after we release 6.0 to upgrade the version.

**Comment by hoytak** [comment]
Marking this as 6.0 and p1 to make sure we don't let it slip.  @nickjong -- would you sign off on this?  This just pins it to the non-beta 3.0 version. Beta eggs are often not kept up after the actual egg is released.  This may not be the case with the coremltools package, but depending on them when the full version is released is bad practice in general.

**Comment by TobyRoseman** [comment]
> This one is the low-risk change for 6.0, the other PR can go in after we release 6.0 to upgrade the version.

But then we'll be running our unit tests using a different set of dependency than our users get.

**Comment by hoytak** [comment]
> > This one is the low-risk change for 6.0, the other PR can go in after we release 6.0 to upgrade the version.
> 
> But then we'll be running our unit tests using a different set of dependency than our users get.

I'm not sure what you mean here ?

**Comment by TobyRoseman** [comment]
> > > This one is the low-risk change for 6.0, the other PR can go in after we release 6.0 to upgrade the version.
> > 
> > 
> > But then we'll be running our unit tests using a different set of dependency than our users get.
> 
> I'm not sure what you mean here ?

@hoytak - We run our unit tests via the `test_wheel.sh` script. This uses the `install_python_toolchain.sh` [to create its' virtual environment](https://github.com/apple/turicreate/blob/ab8bdf42a62baeb8b66c753fbdfdfd944234869d/scripts/test_wheel.sh#L80). `install_python_toolchain.sh` use [the requirement file that you're editing to install its' dependencies](https://github.com/apple/turicreate/blob/ad9c748aa4b255f3c57f6a08da967d9785073664/scripts/install_python_toolchain.sh#L39).

So if we make this change without also making #2775, we will be running unit tests using a different version of `coremltools` than our user will get when they install `turicreate`.

I think both this change and #2275 should be the same pull request. What is the purpose of separating these change into two separate pull requests?

**Comment by srikris** [comment]
Closing this PR for the one that checks on coremltools-3.1

**Pull request closed without merging**
