### PR TITLE
Activity Classifier Name Error with Advanced Parameters

### LINKED ISSUE #2689: Activity Classifier Name Error with Advanced Parameters
Stacktrace:
```
File "turicreate/toolkits/activity_classifier/_activity_classifier.py", line 166, in create
    set_keys = set(params.keys())
NameError: name 'params' is not defined
```
[`params` does indeed seem not to be defined](https://github.com/apple/turicreate/blob/93335055e6619e8e3eed4a65962c875b921bda48/src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py#L166). It's not immediately clear to me how to fix it.

### PR DESCRIPTION
**Pull request by dhivyaaxim**
This PR resolves #2689 
Activity Classifier Name Error with Advanced Parameters

### CODE REVIEW

**Comment by TobyRoseman** [comment]
@shreyajain17 - can we just remove `**kwargs` entirely from `tc.activity_classifier.create`?

**Comment by shreyajain17** [comment]
> @shreyajain17 - can we just remove `**kwargs` entirely from `tc.activity_classifier.create`?

Good catch! It has no use right now so we should remove it.

**Comment by TobyRoseman** [comment]
@dhivyaaxim - please also remove the `**kwargs` from the `create` definition.

**Comment by hoytak** [comment]
Let's merge this.

**Comment by shreyajain17** [comment]
> Let's merge this.
Should I just merge it?

**Comment by TobyRoseman** [comment]
Thanks @dhivyaaxim

**Pull request merged**
