### PR TITLE
make python code pep8 compliant

### LINKED ISSUE #2312: pep8 compatible code style check before build
I found this in a project of my personal interest and it might help us:
```
# .travis
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```
A universal python coding style consistent with pep8 is super helpful, isn't it?

### PR DESCRIPTION
**Pull request by guihao-liang**
## Upstream dependencies

#2826, which removes redundant MXnet **Python** code after major 6.0 release. 

---

## Goal, goal, goal, ale, ale, ale

partially resolve #2312 

1. make our current python codebase fully pep8 compatible.
2. provide GitHub hook to check pep8 compatibility for future commits.
3. build the team culture for the pep8 coding style for our python codebase.

In order to fully resolve #2312, we need to run a `linter`, which can be only done incrementally. I will cover this later.

---

## Methodology

No magic, but [black][0] magic.

I'm pretty confident about the tool [black][0] and its reformatting result because of,

> Also, as a temporary safety measure, Black will check that the reformatted code still produces a valid AST that is equivalent to the original. This slows it down. If you're feeling confident, use --fast.

---

## Step by step

- [x] make source code pep8 compliant, **excluding docstring**.

[black][0] the `python` dir first to make sure the `test` directory is left intact. If all tests are passed, I'm confident to move to the next step.

current `tox.ini` setting,

```bash
[flake8]
max-line-length = 88
```

Just let me know what errors you think should be ignored by the linter and black.

```
All done! ✨ 🍰 ✨
281 files reformatted, 17 files left unchanged.
```

---

- [x] make test code pep8

[0]: https://github.com/psf/black
[1]: https://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by srikris** [comment]
I've usually seen that in the past, the only way to keep this is to actually make the build fail if otherwise :) does this PR also come with a linter?

**Comment by guihao-liang** [comment]
> I've usually seen that in the past, the only way to keep this is to actually make the build fail if otherwise :) does this PR also come with a linter?

Tech has advanced a lot. This is a full context python formatter. I actually pushed it to the internal pipeline. So far so promising.

No linter. This is only a formatter. Linter cannot be done in one shot but incrementally by our team effort.

**Comment by guihao-liang** [comment]
The reason behind changing single quotes to double quotes (cited from pep8):

In Python, **single-quoted strings and double-quoted strings are the same**. This PEP does not make a recommendation for this. Pick a rule and stick to it.

When a string contains single or double quote characters, however, **use the other one to avoid backslashes in the string**. It improves readability.

**For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257.**

**Comment by guihao-liang** [comment]
[W503](https://www.flake8rules.com/rules/W503.html): line break before a binary operator. People tend to disable it. I think it quite reasonable to adopt the new behavior.

old
```python
income = (gross_wages
          + taxable_interest)
```

new

```python
income = (gross_wages +
          taxable_interest)
```

Personally, I think the new behavior is more mentally comfortable.

**Comment by guihao-liang** [comment]
Some people tend to ignore [E203](https://www.flake8rules.com/rules/E203.html),

Anti-pattern
```
with open('file.dat') as f :
    contents = f.read()
```

Best practice (compliant with pep8)

```
with open('file.dat') as f:
    contents = f.read()
```

**Comment by guihao-liang** [comment]
Again, I have to reiterate the main reason that I believe this tool can make it happen,
> In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.

> Also, as a temporary safety measure, Black will check that the reformatted code still produces a **valid AST that is equivalent to the original**. This slows it down. If you're feeling confident, use --fast.

**Comment by guihao-liang** [comment]
With linter enabled,

```
(tc58) ➜  gui-1-36 git:(01-18-pep8-compatible) ✗ python -m flake8 --config tox.ini drawing_classifer.py
drawing_classifer.py:11:1: F401 'numpy as _np' imported but unused
drawing_classifer.py:12:1: F401 'time as _time' imported but unused
drawing_classifer.py:14:1: F401 'turicreate.toolkits._model.CustomModel as _CustomModel' imported but unused
drawing_classifer.py:16:1: F401 'turicreate.toolkits._model.PythonProxy as _PythonProxy' imported but unused
drawing_classifer.py:17:1: F401 'turicreate.toolkits.evaluation as _evaluation' imported but unused
drawing_classifer.py:21:1: F401 'turicreate.extensions as _extensions' imported but unused
drawing_classifer.py:23:1: F401 'six.moves.reduce as _reduce' imported but unused
drawing_classifer.py:175:24: F821 undefined name 'params'
drawing_classifer.py:180:9: F821 undefined name 'params'
drawing_classifer.py:202:5: F401 'turicreate.toolkits.libtctensorflow' imported but unused
drawing_classifer.py:225:89: E501 line too long (97 > 88 characters)
```

We can reduce a lot of redundant imports and unused variables.

**Comment by guihao-liang** [comment]
> With linter enabled,
> 
> ```
> (tc58) ➜  gui-1-36 git:(01-18-pep8-compatible) ✗ python -m flake8 --config tox.ini drawing_classifer.py
> drawing_classifer.py:11:1: F401 'numpy as _np' imported but unused
> drawing_classifer.py:12:1: F401 'time as _time' imported but unused
> drawing_classifer.py:14:1: F401 'turicreate.toolkits._model.CustomModel as _CustomModel' imported but unused
> drawing_classifer.py:16:1: F401 'turicreate.toolkits._model.PythonProxy as _PythonProxy' imported but unused
> drawing_classifer.py:17:1: F401 'turicreate.toolkits.evaluation as _evaluation' imported but unused
> drawing_classifer.py:21:1: F401 'turicreate.extensions as _extensions' imported but unused
> drawing_classifer.py:23:1: F401 'six.moves.reduce as _reduce' imported but unused
> drawing_classifer.py:175:24: F821 undefined name 'params'
> drawing_classifer.py:180:9: F821 undefined name 'params'
> drawing_classifer.py:202:5: F401 'turicreate.toolkits.libtctensorflow' imported but unused
> drawing_classifer.py:225:89: E501 line too long (97 > 88 characters)
> ```
> 
> We can reduce a lot of redundant imports and unused variables.

We should run the linter before starting our unit test.

Currently, all E501 is caused by very long docstrings. 

> You can also increase it, but remember that people with sight disabilities find it harder to work with line lengths exceeding 100 characters. It also adversely affects side-by-side diff review on typical screen resolutions. Long lines also make it harder to present code neatly in the documentation or talk slides.

**Comment by guihao-liang** [comment]
the current number of linter error

```bash
(tc58) ➜  gui-1-36 git:(01-18-pep8-compatible) ✗ python -m flake8 --config tox.ini src/python | wc -l
    2423

```

**Comment by jakesabathia2** [comment]
good!

**Comment by znation** [comment]
@guihao-liang Is there a plan (I assume after this PR) to run `black` automatically on every commit? Or a team culture/documented approach to running it manually that we should plan to adopt?

**Comment by guihao-liang** [comment]
> @guihao-liang Is there a plan (I assume after this PR) to run `black` automatically on every commit? Or a team culture/documented approach to running it manually that we should plan to adopt?

Yes, there's a plan to run `flake8` as git pre-hook. But there are too many errors reported by `flake8`. I would expect it will take some time to get it set up.

**Comment by znation** [comment]
> Yes, there's a plan to run `flake8` as git pre-commit hook. But there are too many errors reported by `flake8`. I would expect it will take some time to get it set up.

What's the relationship between `black` and `flake8`? It was my understanding this PR is all about `black`?

**Comment by guihao-liang** [comment]
> > Yes, there's a plan to run `flake8` as git pre-commit hook. But there are too many errors reported by `flake8`. I would expect it will take some time to get it set up.
> 
> What's the relationship between `black` and `flake8`? It was my understanding this PR is all about `black`?

`black` is a formatter tool and `flake8` is a linter, which is a bundle of tools listed below,
* PyFlakes
* pycodestyle
* Ned Batchelder's McCabe script

The [workflow in this blog](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) should be our workflow too.

**Comment by znation** [comment]
@guihao-liang I think the end goal is admirable, but I'd like to see a better separation of concerns in the PRs that implement it. Can you please clarify the goal of this particular PR -- is it to implement just `black`, `black + flake8`, or something else? While that blog post describes a great end goal to get to, I don't think we should attempt to do it all in one PR (and this PR in particular doesn't appear to).

**Comment by guihao-liang** [comment]
> @guihao-liang I think the end goal is admirable, but I'd like to see a better separation of concerns in the PRs that implement it. Can you please clarify the goal of this particular PR -- is it to implement just `black`, `black + flake8`, or something else? While that blog post describes a great end goal to get to, I don't think we should attempt to do it all in one PR (and this PR in particular doesn't appear to).

The pr is to just verify whether `black` works for us or not (from the current test pipeline result, yes) and format our current codebase.

Later I will,
* provide the pre-commit formatting with `black`.
* figure out a way to enable `flake8`.
* add `flake8` as part of the pre-commit hook.

The overall pipeline should be similar to this

**Comment by guihao-liang** [comment]
```bash
(tc58) ➜  gui-1-36 git:(01-18-pep8-compatible) ✗ git commit -m "dummy"
black....................................................................Failed
- hook id: black
- exit code: 123

error: cannot format drawing_classifer.py: Cannot parse: 11:0:     `turicreate.drawing_classifier.create` and raises a ToolkitError if
Oh no! 💥 💔 💥
1 file failed to reformat.

```
configure pre-commit hook with black is quite easy.

**Comment by guihao-liang** [comment]
passed internal tests for both source-only and all python source. Ready to merge. Need one more review from @TobyRoseman.

**Pull request merged**
